spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/assignment
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: 26905031
  jpa:
    hibernate:
      ddl-auto: none
      properties:
        hibernate:
#          show_sql: true
          format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
